version: 0.0
os: linux
files:
  - source: /
    destination: /root/myapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300